openwisp_radius/models.py

Connecting signals in this way is not as good as doing it in ready
method of the AppConfig.
Commits made in django-freeradius make this line unnecessary and we can
remove this.
Fixes #9

[models.py] Removed signal #9

---

openwisp_radius/api/views.py
openwisp_radius/tests.py

Note: the ```start time``` filter is from the inherited class(tests fail otherwise as they're expected to  be sorted). Should I call ```super()``` and then filter over it instead? 
Implements and closes #19

[api] Accounting API now restricts records by organization id in token

---

runtests.py

I have added tabulation before [this line](https://github.com/openwisp/openwisp-radius/blob/master/runtests.py#L15), because in the previous version `execute_from_command_line(args)` line wasn't in if statement.

[runtests.py] Added indentation

---

requirements-test.txt
tests/settings.py

[settings] Enable CORS in django rest framework for cross-domain ajax requests

---

.travis.yml

Fixes : 
- [warn] on root: deprecated key: "sudo" (The key `sudo` has no effect anymore.)

[travis] Fix warnings

---

.gitignore
openwisp_radius/migrations/__init__.py
openwisp_radius/tests/mixins.py
openwisp_radius/tests/tests.py

Auto create OrganizationRadiusSettings object for the default organizaiton.
Fixes #71

[bug] Radius token for initial default org not created #71

---

tests/openwisp2/sample_users/migrations/0002_default_groups_and_permissions.py

@atb00ker this is why the build was failing. Administrators are now allowed to delete users of their org (before they weren't which was weird).

[tests] Run update_admins_permissions in sample_users app

---

openwisp_radius/api/views.py

This was changed mistakenly during the Google Code-In (https://github.com/openwisp/openwisp-radius/commit/7803b91eba92447363ad604129d728f7d55b842b#diff-d40baa932501d0655680443a6bf8b008R30)
and the mistake went unnoticed (@cking100 FYI).

[api] Fixed broken cache check in TokenAuthentication

---

.travis.yml
docs/source/user/api.rst
openwisp_radius/api/views.py
openwisp_radius/tests/test_api.py

[api] Use BearerAuthentication #91

---

docs/source/user/api.rst
docs/source/user/enforcing_limits.rst
openwisp_radius/api/serializers.py
openwisp_radius/api/urls.py
openwisp_radius/api/views.py
openwisp_radius/base/models.py
openwisp_radius/tests/__init__.py
openwisp_radius/tests/mixins.py
openwisp_radius/tests/test_admin.py
openwisp_radius/tests/test_api.py
openwisp_radius/tests/test_commands.py
openwisp_radius/tests/test_models.py

[bug] Fix API prefix add error #132

---

openwisp_radius/api/views.py

Found a solution for https://github.com/axnsan12/drf-yasg/issues/626

[ui/ux] API docs empty serializer section removed

---

docs/source/developer/how_to_extend.rst
run-qa-checks
runsphinx-build

The runsphinx-build created the build files in ./docs/build instead of
./docs/build/html like `make html` does.
This inconsistency caused that pylinkvalidator didn't spot internal
links returning 404.
Note: the crawler we use does not check external resources by default.
I gave it a run to check external resources and found 1 broken link to github, but I think we cannot do this in the build because the process is too slow.

[qa] Improve 404 broken link check

---

.github/workflows/ci.yml
docs/source/developer/setup.rst

Based on my understanding, the new pip dependency resolver
fixes this. So in this module we can guide our users
through the installation steps to install a recent version
of pip and they should not incur in this issue and the
CI build will confirm this.
Fixes #244

[fix] Ensure DRF requirement is respected #244

---

tests/openwisp2/settings.py

Added `openwisp_users.accounts` to override default allauth-templates.
Closes #243

[bug] Email confirmation fix #243

---

openwisp_radius/api/serializers.py
openwisp_radius/api/views.py
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_api/test_rest_token.py

Added `RadiusUserSerializer` which returns the user data in the obtain and validate token views.

[change] Return user data in token views (obtain & validate)

---

openwisp_radius/api/views.py
openwisp_radius/tests/test_api/test_rest_token.py

Merge the response data of validate token view with TokenSerializer, which since it's configurable allows customizing the response if needed.

[refactor] Use rest_auth_settings.TokenSerializer in validate token view

---

openwisp_radius/api/views.py
openwisp_radius/tests/test_api/test_api.py

dj_rest_auth==2.1.6 uses utlity functions of allauth instead of Django when
allauth is present in INSTALLED_APPS. Therefore, API views of openwisp-radius
were upadted to use utility functions of allauth.
Without this change, the test suite was failing
Closes #266

[change!] Use utility functions of allauth #266

---

docs/source/user/settings.rst
openwisp_radius/api/freeradius_views.py
openwisp_radius/registration.py
openwisp_radius/tests/test_api/test_freeradius_api.py

This is needed to implement payment flows in which the user
needs to reach the website of their bank or, more in general,
whenever a registration method needs the user to complete
the final part of the registration online on website URLs
which cannot be predicted and hence cannot be added to
the walled garden.

[feature] Allow specific methods to authorize unverified users

---

openwisp_radius/apps.py
openwisp_radius/settings.py
openwisp_radius/tests/test_admin.py
requirements.txt
tests/openwisp2/settings.py

Registered menu groups
closes #260

[enhancement] Registered menu groups #260

---

openwisp_radius/api/serializers.py
openwisp_radius/tests/mixins.py
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_api/test_phone_verification.py

If a user tries to register with username and phone number which
are already in use, only the username error is shown because
django rest auth has a validation method for this field,
but for the phone number uniqueness we rely on model validation,
which is not performed if the serializer level validation fails.
Adding a validation level serialzier for phone number too,
so that both username and phone_number are incldued in
the error response.

[fix] Added validation of phone number uniqueness

---

openwisp_radius/api/views.py
openwisp_radius/tests/test_api/test_phone_verification.py

If user has registered with only phone number, the user will have
only phone number as username. If the user updates the phone_number,
then the username of the user will also get updated.
Closes #282

[change/fix] Update username when phone number is changed #282

---

openwisp_radius/api/freeradius_views.py
openwisp_radius/tests/test_api/test_freeradius_api.py

Used authentication backend of openwisp-users to filter users with the username,
email and mobile phone.
Also, added a failing test for this.
Fixes #292

[fix] Used openwisp-users auth backend to filter user in FreeradiusAPIAuthentication #292

---

openwisp_radius/api/freeradius_views.py
openwisp_radius/tests/test_api/test_freeradius_api.py

Earlier, forbidden was showing because username is missing while doing
FreeradiusApiAuthentication. Fixed this behaviour by skipping check for
username when status type is unsupported.
Fixes #298

[fix] Accounting-On status type with blank username returns 403 #298

---

docs/source/user/api.rst
openwisp_radius/api/urls.py

#302 
changed the endpoint /api/v1/radiusbatch and
/api/v1/radius/organization/{slug}/radiusbatch/{id}/pdf
and updated the radiusbatch documentation in API Documentation

[change!] Renamed URL of radius batch endpoint #302

---

openwisp_radius/api/serializers.py
openwisp_radius/tests/test_api/test_phone_verification.py

This method took for granted the presence of specific keys in the sent data,
but that can break, this patch fixes this issue by checking for the presence
of the key not only in error_dict but also in data.

[fix] Fixed KeyError in RegisterSerializer.validate_cross_org_registration

---

.github/workflows/ci.yml
docs/source/developer/signals.rst
docs/source/index.rst
docs/source/user/api.rst
openwisp_radius/api/freeradius_views.py
openwisp_radius/signals.py
openwisp_radius/tests/test_api/test_freeradius_api.py
setup.py

[feature] Emit signal in freeradius accounting view #341

---

openwisp_radius/base/models.py
openwisp_radius/tests/test_batch_add_users.py

@atb00ker This commit adds a check such that the prefix in a batch user creation only accepts letters, numbers and the special characters @/./+/-/_

[change] Adds check for valid prefix in batch creation #365

---

openwisp_radius/api/freeradius_views.py
openwisp_radius/tests/test_api/test_freeradius_api.py

Added handling of "Interim-Updates" for RadiusAccounting sessions
that are closed by OpenWISP when user logs into another organization.
Fixes #322

[fix] Fixed handling of interim-updates for closed sessions #322

---

openwisp_radius/tests/test_api/test_freeradius_api.py

- Used **openwisp-utils** `@capture_any_output()` to avoid noisy
error logging output produced during tests.
- Disable noisy logging warnings in `TestFreeradiusApi`.
Closes #377

[tests] Avoided noisy error logging during tests #377

---

openwisp_radius/api/serializers.py
openwisp_radius/tests/test_api/test_api.py

Cross organization registration validated failed when regiration
data belonged to two different users.
Now, it handles this case by selecting the first object from the
query.

[fix] Fixed cross organization registration for multiple user accounts

---

docs/source/developer/setup.rst
openwisp_radius/locale/de/LC_MESSAGES/django.po
openwisp_radius/locale/fur/LC_MESSAGES/django.po
openwisp_radius/locale/it/LC_MESSAGES/django.po
openwisp_radius/locale/ru/LC_MESSAGES/django.po
openwisp_radius/locale/sl/LC_MESSAGES/django.po
openwisp_radius/tasks.py
openwisp_radius/templates/radius_accounting_start.html
openwisp_radius/tests/test_tasks.py
tests/openwisp2/settings.py

Updated radius_accounting_start email to indicate duration of validity of link
only if SESAME_MAX_AGE is not None.
Closes #379
Signed-off-by: Aryaman <aryamanz29@gmail.com>
[chores] Adjustments to accounting start email sesame text #379
Related to #379
Co-authored-by: Federico Capoano <f.capoano@openwisp.io>

[change] Updated accounting start email to indicate duration #379

---

openwisp_radius/management/commands/base/delete_unverified_users.py

The code (queryset and output massage) didn't take into account the possibility of exclude_methods not being passed, I fixed that.

[fix] Delete unverified users: ignore exclude_methods if not present

---

CHANGES.rst
openwisp_radius/management/commands/base/convert_called_station_id.py
openwisp_radius/tests/test_commands.py

- warn > warning (warn is deprecated)
- use warning instead of errors for more
temporary connection issues cases

[chores] Called station id: use logger.warning instead of warn or error for temporary connection issues

---

openwisp_radius/api/serializers.py
openwisp_radius/tests/test_admin.py
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_api/test_phone_verification.py
requirements-test.txt
tests/openwisp2/settings.py

Fixed bug in allowed mobile prefix implementation:
The implementation was joining the globally allowed prefixes
and the prefixes allowed at org level, with the result
that disabling a prefix at org level was not possible.
Added admin tests for default values of fallback fields #46.
Bound openwisp-utils in requirements-tests.txt.

[misc] Added tests and fixed bug in allowed mobile prefix API validation

---

openwisp_radius/saml/views.py

In some cases, it possible that the organization cache for
the user is not updated before execution of the following
code. Hence, the cache is manually updated here.

[fix] Fixed organization cache bug in SAML ACS view 

---

openwisp_radius/base/models.py
openwisp_radius/tests/test_models.py

The previous implementation used the "os" module for deleting resisdual
csv files. This causes issues when the project uses a file storage backend
other than based on file system.

[fix] Use storage backend method for deleting RadiusBatch.csvfile

---

openwisp_radius/admin.py
openwisp_radius/tests/test_admin.py

Bug:
Accessing admin change view of a non-existent RadiusBatch object
resulted in Server Error 500 because the "DoesNotExist"
conditioned was not handled.

[fix] Added error handling in RadiusBatch admin change view

---

openwisp_radius/base/models.py
openwisp_radius/management/commands/base/cleanup_stale_radacct.py
openwisp_radius/tests/test_commands.py

- Added "RadiusAccounting.close_stale_sessions" class method for
closing stale sessions
- The method takes into account the "update_time" time of the
session
- If the "update_time" is recent, then the session is not closed
even when the "start_time" is older than the specified time.
The "start_time" of a session is only checked when the
"update_time" is not set.
Closes #426

[change] Improved cleanup stale session command #426

---

openwisp_radius/apps.py
openwisp_radius/receivers.py
openwisp_radius/tests/test_models.py

Whenever a new session is started, all previous open session from the same user and called-station-id is closed.
Closes #437

[feature] Close previous open sessions with same MAC #437

---

openwisp_radius/base/models.py
openwisp_radius/tests/test_commands.py

Bug:
RadiusAccounting.close_stale_sessions was updating all session instead of only open sessions.
Fix:
Fixed the query in RadiusAccounting.close_stale_sessions and added an automated test.

[fix] Fixed RadiusAccounting.close_stale_sessions

---

openwisp_radius/api/serializers.py
openwisp_radius/tests/test_api/test_freeradius_api.py

The accounting stop REST API operation was not taking into account the OPENWISP_RADIUS_DISPOSABLE_RADIUS_USER_TOKEN setting when disabling the auth capability of the radius token.

[fix] Honor DISPOSABLE_RADIUS_USER_TOKEN in accounting stop API view

---

.github/workflows/ci.yml
openwisp_radius/__init__.py
openwisp_radius/api/serializers.py
openwisp_radius/api/views.py
openwisp_radius/apps.py
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_token.py
requirements-test.txt
setup.py
tests/openwisp2/sample_radius/__init__.py
tests/openwisp2/sample_radius/apps.py
tests/openwisp2/sample_users/__init__.py
tests/openwisp2/sample_users/apps.py
tests/openwisp2/settings.py

- Dropped support for Django 4.0
- Dropped support for Python 3.7
- Bumped weasyprint~=59.0
- Bumped dj-rest-auth~=4.0.1
**Important**: dj-rest-auth>3 changed configuration settings. It is recommended to review your Django project settings while upgrading.
**Blockers**

[deps] Added support for Django 4.1 and Django 4.2

---

.github/workflows/ci.yml
openwisp_radius/settings.py
openwisp_radius/tests/test_users_integration.py
tests/openwisp2/sample_users/management/commands/export_users.py

Added 'registered_user.method' and 'registed_user.is_verified' to OPENWISP_USERS_EXPORT_USERS_COMMAND_CONFIG setting.
**Blockers**

[feature] Extended OPENWISP_USERS_EXPORT_USERS_COMMAND_CONFIG

---

docs/source/user/settings.rst
openwisp_radius/api/serializers.py
openwisp_radius/settings.py
openwisp_radius/tests/test_api/test_phone_verification.py

I changed the code to check whether phone_number provided is a Mobile number and raise expception if not. (#484 )
Below is the function code that I have altered. 
```
def validate_phone_number(self, phone_number):
org = self.context['view'].organization
if get_organization_radius_settings(org, 'sms_verification'):
if phonenumbers.phonenumberutil.number_type(phone_number) != 1:
raise serializers.ValidationError(_('Landline numbers can\'t be used to send SMS.'))
if not phone_number:
raise serializers.ValidationError(_('This field is required.'))
mobile_prefixes = org.radius_settings.allowed_mobile_prefixes_list
if not self.is_prefix_allowed(phone_number, mobile_prefixes):
raise serializers.ValidationError(
_('This international mobile prefix is not allowed.')
)
if …
```

Bug Fix: Different types of phone numbers are allowed, but only mobile types should

---

openwisp_radius/tests/mixins.py
openwisp_radius/tests/test_api/test_freeradius_api.py

I wanted to double check the radius token cache would be cleared if the user authenticates with another organization.

[test] Added test for radius token cache and multiple orgs

---

docs/source/user/enforcing_limits.rst
openwisp_radius/api/freeradius_views.py
openwisp_radius/tests/test_api/test_freeradius_api.py

This will signal that no reply should be added to the response. Useful for raising MaxQuotaReached for on custom conditions which do not necessarily have a related reply message that can be interpreted by the NAS.

[change] Allow check method of counters to return None

---

openwisp_radius/base/models.py
openwisp_radius/tests/test_tasks.py

[fix] Use date_joined if last_login is None for deleting inactive users
----------------------
[fix] Don't unverify inactive users with unspecified, manual and email methods #517
Users registered with unspecified, manual and email methods don't have
an option to re-verify. Thus, exclude them when unverifying inactive
users.
Fixes #517

[fix] Issues with unverify and delete inactive users (last_login=None and registration method) #517

---

tests/openwisp2/sample_users/migrations/0001_initial.py

[chores] Made compatible with django-allauth~=0.63.0

---

.github/workflows/ci.yml
openwisp_radius/templates/djangosaml2/auth_error.html
openwisp_radius/templates/djangosaml2/login_error.html
openwisp_radius/templates/djangosaml2/logout_error.html
openwisp_radius/templates/djangosaml2/wayf.html
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_api/test_phone_verification.py
requirements-test.txt
setup.py
tests/openwisp2/settings.py

[deps] Allauth update, openwisp-utils ~= 1.1.0

---

openwisp_radius/locale/de/LC_MESSAGES/django.po
openwisp_radius/locale/fur/LC_MESSAGES/django.po
openwisp_radius/locale/it/LC_MESSAGES/django.po
openwisp_radius/locale/ru/LC_MESSAGES/django.po
openwisp_radius/locale/sl/LC_MESSAGES/django.po
openwisp_radius/saml/urls.py
openwisp_radius/saml/views.py
openwisp_radius/templates/djangosaml2/login_additional_info.html
openwisp_radius/tests/test_saml/test_views.py
tests/openwisp2/sample_radius/saml/views.py

If the IdP does not include email address in SAML response, then the user will be asked for email during sign-up.

[feature] Added view to collect email in SAML registration

---

openwisp_radius/integrations/monitoring/templates/admin/config/radius-monitoring/device/change_form.html

Previously, the `device change_form.html` template extended `config/device/change_form.html`. However, after merging the device deactivation feature, the inheritance order was modified. As a result, enabling the Radius integration caused the "Status" and "Charts" tabs to disappear from the device page.

[fix] Updated device change_form template

---

CHANGES.rst
openwisp_radius/__init__.py

1.1.0 release

---

openwisp_radius/api/freeradius_views.py

Allows customizing the reply message when MaxQuotaReached is triggered.
Before it was hardcoded.
- N/A I have updated the documentation.

[change] Allow overriding RADIUS reply-message on MaxQuotaReached

---

openwisp_radius/base/models.py
openwisp_radius/tests/test_admin.py

Closes #604 
The crash happened because the `clean()` method tried to validate using the parent group before that group was actually saved, which caused the ValidationError.
Fixed it by:
* Skip `clean()` validation when the parent group hasn’t been saved yet (fixes error when creating a new group).
* Add a `save()` method to ensure `groupname` is populated from the parent’s name before saving (prevents empty strings).

[fix] Error when creating RadiusGroup with inlines (#604)

---

.github/workflows/ci.yml
openwisp_radius/api/serializers.py
openwisp_radius/counters/base.py
openwisp_radius/counters/resets.py
openwisp_radius/tests/test_api/test_api.py
openwisp_radius/tests/test_counters/test_base_counter.py
openwisp_radius/tests/test_counters/test_sqlite_counters.py
openwisp_radius/tests/test_selenium.py
openwisp_radius/utils.py

[change] Allow counters to return multiple replies #634
