openwisp/openwisp-radius

- openwisp_radius/admin.py
- openwisp_radius/api/views.py
- openwisp_radius/social/views.py
- openwisp_radius/tests.py
- openwisp_radius/urls.py
- requirements.txt
- tests/settings.py
Added support for social login.
> Social login

- openwisp_radius/models.py
- openwisp_radius/tests.py
> [batch] Fix batch users not being assigned an organization.

- openwisp_radius/admin.py
- openwisp_radius/tests/test_users_integration.py
[tests] Added `TestUsersIntegration` #1
> [tests] Added TestUsersIntegration #1

- .travis.yml
- requirements-test.txt
> [qa] Added message style check #36

- .coveragerc
- openwisp_radius/api/views.py
- openwisp_radius/tests/tests.py
- requirements-test.txt
> [qa] Increase test coverage to 100%

- .travis.yml
- openwisp_radius/admin.py
- requirements.txt
> [admin] Updated AlwaysHasChangedForm #18

- openwisp_radius/tests/tests.py
> Add unit test for batch creation operation performed via API

- openwisp_radius/tests/tests.py
Created a multitenancy env in which all the objects needed for the
moment to perform the tests.
Created a test for radiuscheck queryset and radiuscheck organization fk.
Fixes #2
> [admin] Add tests for multitenancy #2

- openwisp_radius/api/serializers.py
- openwisp_radius/api/urls.py
- openwisp_radius/api/views.py
- openwisp_radius/templates/custom_password_reset_email.html
- openwisp_radius/tests/tests.py
- tests/settings.py
> [api] Add reset and change password endpoints #44

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [bug] Fixes AttributeError in PasswordResetView #51

- openwisp_radius/api/urls.py
- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [api] add support for validate auth token api #57

- .travis.yml
- openwisp_radius/api/views.py
- openwisp_radius/apps.py
- openwisp_radius/management/commands/__init__.py
- openwisp_radius/models.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/tests.py
- setup.py
Added support for django 2.2 and added tests for
python 3.6 and 3.7 in travis
Fixes #59
> [requirements] Added support for django 2.2 #59

- .travis.yml
- requirements-test.txt
- runcheckmigration
- runflake8
- runisort
Replace old qa checks with `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)
> [qa] Replace with openwisp-utils-qa-checks

- .travis.yml
- openwisp_radius/migrations/0002_initial_openwisp_radius.py
- openwisp_radius/models.py
- openwisp_radius/tests/tests.py
- requirements-test.txt
Removed the logics which were duplicated
in the others modules and redefined it here to enable reusability and ease debugging.
Related to openwisp/openwisp-utils#40
> [django] Generalize url/key logic

- .travis.yml
- openwisp_radius/tests/test_api.py
- openwisp_radius/tests/tests.py
- requirements.txt
Added support for Django 3.0
Bumped openwsip-user to 0.2.0
Fixes #79
> [deps] Added support for Django 3.0

- docs/source/general/api.rst
- docs/source/general/freeradius.rst
- docs/source/general/registration.rst
- docs/source/general/setup.rst
- openwisp_radius/api/urls.py
- openwisp_radius/api/views.py
- openwisp_radius/settings.py
- openwisp_radius/tests/test_api.py
- requirements-test.txt
- tests/openwisp2/sample_radius/api/views.py
- tests/openwisp2/sample_radius/tests.py
Documentation + bugfixes + user radius sessions.
> [api/radius] Documentation + bugfixes + user radius sessions

- .travis.yml
- README.rst
- docs/source/index.rst
- openwisp_radius/base/models.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_api.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_models.py
- openwisp_radius/utils.py
- run-qa-checks
> [chores/gsoc2020] clean-up #90

- openwisp_radius/settings.py
Similar to https://github.com/openwisp/openwisp-network-topology/pull/67
> [improvement] Seperate logger name for settings

- docs/source/developer/how_to_extend.rst
- docs/source/developer/setup.rst
- openwisp_radius/admin.py
- openwisp_radius/private_storage/views.py
- openwisp_radius/tests/test_models.py
- openwisp_radius/urls.py
- tests/openwisp2/urls.py
I need to go fast with this @atb00ker. If you find things to improve and I have already merged, please open another PR.
> [fix] Fixed backward compatibility in openwisp_radius.urls

- openwisp_radius/api/serializers.py
- openwisp_radius/social/views.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_api.py
- openwisp_radius/tests/test_models.py
Made changes required due to incompatibility introduced in https://github.com/openwisp/openwisp-users/pull/140
> [deps] openwisp-users master branch update

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [api] Update last_login in ObtainAuthTokenView #112

- docs/source/user/api.rst
- openwisp_radius/api/urls.py
- openwisp_radius/api/views.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/test_api.py
> [fix] BatchView permission and authorization #94

- docs/source/conf.py
- openwisp_radius/admin.py
- openwisp_radius/api/serializers.py
- openwisp_radius/api/views.py
- openwisp_radius/apps.py
- openwisp_radius/base/admin_actions.py
- openwisp_radius/base/admin_filters.py
- openwisp_radius/base/forms.py
- openwisp_radius/base/models.py
- openwisp_radius/base/validators.py
- openwisp_radius/management/commands/base/batch_add_users.py
- openwisp_radius/management/commands/base/cleanup_stale_radacct.py
- openwisp_radius/management/commands/base/delete_old_postauth.py
- openwisp_radius/management/commands/base/delete_old_radacct.py
- openwisp_radius/management/commands/base/delete_old_users.py
- openwisp_radius/management/commands/base/prefix_add_users.py
- openwisp_radius/migrations/__init__.py
- openwisp_radius/settings.py
- openwisp_radius/social/views.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_api.py
- openwisp_radius/tests/test_models.py
- openwisp_radius/tests/test_social.py
- openwisp_radius/urls.py
- openwisp_radius/utils.py
- setup.py
> [minor] Clean up

- .travis.yml
- openwisp_radius/migrations/__init__.py
- tests/openwisp2/sample_radius/migrations/0002_initial_openwisp_app.py
- tests/openwisp2/sample_radius/migrations/0003_default_groups_and_permissions.py
https://github.com/openwisp/openwisp-radius/pull/142 is merged but was incomplete and had problems in migrations, fixed it here.
> [fix] Fix hardcoded path in migration

- .gitignore
- docs/source/developer/how_to_extend.rst
- docs/source/developer/setup.rst
- openwisp_radius/tasks.py
- openwisp_radius/tests/__init__.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_tasks.py
- requirements.txt
- tests/openwisp2/__init__.py
- tests/openwisp2/celery.py
- tests/openwisp2/settings.py
> [enchancement] celery-beat for management commands #117

- openwisp_radius/api/serializers.py
- openwisp_radius/tests/test_api.py
> [bug] Honor Postauth password length #116

- openwisp_radius/api/urls.py
- openwisp_radius/tests/test_api.py
> [api] Change freeradius endpoint urls #146

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
Fixed improper use of the django ORM `get()` manager method, which raises error when multiple objects are returned.
By definition, `RadiusAccounting` objects are many and the code must deal with the case in which multiple objects are returned, selecting only the last open relevant session.
> [fix] Fixed regression in _radius_accounting_nas_stop

- openwisp_radius/admin.py
Related to https://github.com/openwisp/ansible-openwisp2/issues/216
> [fix] Removed static() call from media assets

- openwisp_radius/api/serializers.py
- openwisp_radius/base/forms.py
- openwisp_radius/tests/test_api.py
> [fix] Fixed password reset for inactive users #181

- .gitignore
- docs/source/user/settings.rst
- openwisp_radius/api/views.py
- openwisp_radius/settings.py
- tests/openwisp2/settings.py
> [fix] Fixed default password reset url and added its documentation #182

- openwisp_radius/api/views.py
- openwisp_radius/base/models.py
- openwisp_radius/tests/test_api.py
- openwisp_radius/tests/test_token.py
> [fix] Handled phone token validation error #191

- openwisp_radius/api/permissions.py
- openwisp_radius/api/serializers.py
- openwisp_radius/api/utils.py
- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [api] Disable endpoints for organizations without SMS verification #189

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [feature] Added email to the response of validateAuthTokenView #201

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
> [api] Reduce queries for radius_settings #195

- openwisp_radius/tests/test_api.py
The test `test_registration_with_jwt` is failing for a bug that seems to be caused in the jwt token library.
> [tests] Fix jwt token test

- openwisp_radius/api/serializers.py
- openwisp_radius/tests/test_api.py
- requirements.txt
> [feature] Added UserAuthenticationBackend to login api #209 

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api.py
- requirements.txt
> [feature] Added authorization by email and phone number #205

- openwisp_radius/api/swagger.py
- runtests.py
- tests/openwisp2/integrations/tests.py
- tests/openwisp2/settings.py
- tests/openwisp2/urls.py
Fixed swagger API docs collision with openwisp-users.
> [fix] Fixed swagger API docs collision with openwisp-users

- docs/source/user/api.rst
- docs/source/user/settings.rst
- openwisp_radius/admin.py
- openwisp_radius/base/models.py
- openwisp_radius/migrations/0020_added_optional_registration_fields.py
- openwisp_radius/tests/test_api.py
- tests/openwisp2/sample_radius/migrations/0020_added_optional_registration_fields.py
- improved docs
- reduced repetition (admin fields)
- other minor improvements
Related to #220
> [chores] Improvements to PR #220

- .github/workflows/ci.yml
- requirements.txt
Remove Django 2.2 from requirements and travis.
Closes #171
> [deps] Drop support for Django 2.2 #171

- .github/workflows/ci.yml
Fixed CI
relate to https://github.com/openwisp/openwisp-controller/issues/417
> [ci] Fixed CI for django~=3.0.0

- docs/source/user/api.rst
- openwisp_radius/api/views.py
- openwisp_radius/apps.py
> [feature] Added throttling of API requests openwisp#95

- openwisp_radius/admin.py
- requirements-test.txt
- requirements.txt
> [deps] Updated and tested djangorestframework~=3.12 #194

- openwisp_radius/admin.py
OpenWISP Users already does this, although I had to update it: https://github.com/openwisp/openwisp-users/pull/244.
CC: @devkapilbansal @ManishShah120.
> [chores] Avoid redundant unregistration of TokenProxy

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api/test_phone_verification.py
- openwisp_radius/tests/test_api/test_rest_token.py
- tests/openwisp2/sample_radius/tests.py
@devkapilbansal I had to reorder some tests because I couldn't find them.
> [fix] Show phone number as null in ValidateAuthTokenView if None

- openwisp_radius/api/views.py
- openwisp_radius/base/models.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/test_api/test_api.py
- openwisp_radius/tests/test_api/test_phone_verification.py
- tests/openwisp2/sample_radius/tests.py
Paying technical debt, cleaning up and updating the codebase due to recent changes.
> [misc] Cleanup

- docs/source/developer/captive_portal_mock.rst
- docs/source/index.rst
- tests/openwisp2/integrations/tests.py
- tests/openwisp2/urls.py
- tests/openwisp2/views.py
> [tests] Added captive portal mock views #263

- openwisp_radius/receivers.py
- openwisp_radius/tests/test_models.py
> [fix] Fixed radius user group not creation with multiple orgs #227

- docs/source/user/management_commands.rst
- openwisp_radius/management/commands/base/delete_unverified_users.py
- openwisp_radius/management/commands/delete_unverified_users.py
- openwisp_radius/tasks.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_tasks.py
- tests/openwisp2/sample_radius/management/commands/delete_unverified_users.py
> [feature] Added management command and celery task to delete unverified users #279

- openwisp_radius/tests/test_admin.py
closes https://github.com/openwisp/openwisp-utils/issues/251
> [test] Minor changes in test to fix its failure

- .github/workflows/ci.yml
- docs/source/user/management_commands.rst
- docs/source/user/settings.rst
- openwisp_radius/api/serializers.py
- openwisp_radius/management/commands/base/convert_called_station_id.py
- openwisp_radius/management/commands/convert_called_station_id.py
- openwisp_radius/settings.py
- openwisp_radius/tasks.py
- openwisp_radius/tests/static/openvpn.status
- openwisp_radius/tests/test_api/test_freeradius_api.py
- openwisp_radius/tests/test_commands.py
- setup.py
- tests/openwisp2/sample_radius/management/commands/convert_called_station_id.py
Added management command and celery task to convert/correct
called station id of RADIUS session.
Closes #276
____________________________
TODO:
> [feature] [feature] Convert RADIUS accounting CALLED-STATION-ID #276

- .github/workflows/ci.yml
- openwisp_radius/base/models.py
Removed deprecated import and updated CI for python 3.9
Fixes #242
> [fix] Added support for python3.9 #242

- docs/source/user/api.rst
- openwisp_radius/api/exceptions.py
- openwisp_radius/api/permissions.py
- openwisp_radius/api/serializers.py
- openwisp_radius/api/utils.py
- openwisp_radius/api/views.py
- openwisp_radius/base/models.py
- openwisp_radius/tests/test_api/test_api.py
- openwisp_radius/tests/test_api/test_rest_token.py
- openwisp_radius/tests/test_api/test_utils.py
- openwisp_radius/tests/test_models.py
- tests/openwisp2/sample_users/migrations/0001_initial.py
- tests/openwisp2/sample_users/models.py
> [change] Allowed users to sign up to multiple organizations #297

- openwisp_radius/api/serializers.py
- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api/test_api.py
Inherited PasswordChangeView of openwisp-users to add support for current-password in password change
view.
Closes #289
> [change] Improved REST API to change password #289

- docs/source/developer/freeradius.rst
- docs/source/user/api.rst
- docs/source/user/enforcing_limits.rst
- docs/source/user/saml.rst
- docs/source/user/settings.rst
- openwisp_radius/api/freeradius_views.py
- openwisp_radius/counters/base.py
- openwisp_radius/counters/exceptions.py
- openwisp_radius/counters/mysql/daily_counter.py
- openwisp_radius/counters/mysql/daily_traffic_counter.py
- openwisp_radius/counters/postgresql/daily_counter.py
- openwisp_radius/counters/postgresql/daily_traffic_counter.py
- openwisp_radius/counters/resets.py
- openwisp_radius/counters/sqlite/__init__.py
- openwisp_radius/counters/sqlite/daily_counter.py
- openwisp_radius/counters/sqlite/daily_traffic_counter.py
- openwisp_radius/settings.py
- openwisp_radius/tests/mixins.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_api/test_freeradius_api.py
- openwisp_radius/tests/test_api/test_rest_token.py
- openwisp_radius/tests/test_counters/test_base_counter.py
- openwisp_radius/tests/test_counters/test_mysql_counters.py
- openwisp_radius/tests/test_counters/test_postgresql_counters.py
- openwisp_radius/tests/test_counters/test_sqlite_counters.py
- openwisp_radius/tests/test_counters/utils.py
- openwisp_radius/tests/test_social.py
- tests/openwisp2/settings.py
> [feature] Add support for RADIUS group checks and replies (sqlcounter) #164

- docs/source/user/management_commands.rst
- openwisp_radius/management/commands/base/delete_unverified_users.py
- openwisp_radius/tests/test_commands.py
> [change] Changed delete_unverified_users to avoid deleting users which have accounting sessions #348

- openwisp_radius/tests/test_api/test_utils.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_models.py
- openwisp_radius/tests/test_saml/test_views.py
- openwisp_radius/tests/test_tasks.py
- tests/openwisp2/integrations/tests.py
- tests/openwisp2/sample_radius/tests.py
> [chores] Capture errors triggered on purpose during tests #338

- openwisp_radius/migrations/0002_initial_openwisp_radius.py
- openwisp_radius/migrations/__init__.py
- setup.py
> [refactor] Upgrade swapper #347

- docs/source/user/management_commands.rst
- openwisp_radius/management/commands/base/delete_unverified_users.py
- openwisp_radius/tests/test_commands.py
> [change] Exclude staff users from delete_unverified_users #353

- .github/workflows/ci.yml
Needed to run "compilemessages".
> [ci] Added gettext to installed system packages

- setup.py
Added Celery v5 in setup.py and tested all celery tasks.
Closes #188
> [deps] Updated Celery to version 5 #188

- openwisp_radius/api/views.py
- openwisp_radius/tests/test_api/test_phone_verification.py
> [fix] Delete any cached radius token key on phone number change #369

- openwisp_radius/settings.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/urls.py
I tested the API but the API was referenced from admin portal as well in `radiusbatch/<slug>/change/`, I realized this a bit after the PR was merged!
> [fix] Fix url csv from admin portal

- .readthedocs.yaml
> [chores] Added ReadTheDocs configuration #287

- docs/source/user/generating_users.rst
- docs/source/user/saml.rst
- docs/source/user/settings.rst
> [chores] Small fixes and improvements to SAML settings #339

- openwisp_radius/tasks.py
> [openwisp_radius/tasks.py] add celery to tasks #387

- docs/source/user/generating_users.rst
- openwisp_radius/admin.py
- openwisp_radius/base/models.py
- openwisp_radius/templates/openwisp-radius/admin/rad_batch_users_add_form.html
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_batch_add_users.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_tasks.py
> [Fix] Flag user as verified in batch user creation #397

- docs/source/user/settings.rst
> [docs] Documented SMS tokens related settings #273

- openwisp_radius/base/models.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_models.py
> [Fix] Unique attribute for check or reply #335

- docs/source/developer/freeradius.rst
- docs/source/developer/freeradius_wpa_enterprise.rst
- docs/source/index.rst
- docs/source/user/importing_users.rst
> [docs] Documented WPA Enterprise (EAP-TTLS-PAP) setup #163

- openwisp_radius/admin.py
- openwisp_radius/base/fields.py
- openwisp_radius/base/models.py
- openwisp_radius/migrations/0031_added_fallback_model_fields.py
- openwisp_radius/tests/test_admin.py
- openwisp_radius/tests/test_api/test_freeradius_api.py
- tests/openwisp2/sample_radius/migrations/0028_alter_organizationradiussettings_allowed_mobile_prefixes_and_more.py
- Renamed "FallbackBooleanField" to "FallbackBooleanChoiceField"
- Renamed "FallbackCharField" to "FallbackCharChoiceField"
- Made "FallbackTextField" return fallback value if database
contains None. This automatically populates the field in
the admin form.
Closes #410
> [fix] Fixed OrganizationRadiusSetting change form not populating default values #410

- docs/source/user/settings.rst
- openwisp_radius/base/models.py
- openwisp_radius/private_storage/storage.py
- openwisp_radius/private_storage/views.py
- openwisp_radius/settings.py
> [Fix] Made private storage backend configuration #417

- openwisp_radius/management/commands/base/convert_called_station_id.py
- openwisp_radius/tests/test_commands.py
Changed log level for different errors generated by
convert_called_station_id command to "warning".
> [chores] Changed log level for convert_called_station_id

- openwisp_radius/admin.py
> [fix] Load image using `static()` in RegisteredUserInline.get_is_verified

- openwisp_radius/saml/views.py
> [chores] Used `User` model method for invalidation of org cache

- openwisp_radius/private_storage/urls.py
- openwisp_radius/private_storage/views.py
> [fix] Use "path" URL kwarg in "serve_private_file" URL pattern #418

- openwisp_radius/counters/base.py
> [chores] Fixed minor typo in BaseCounter SkipCheck message

- CHANGES.rst
- openwisp_radius/__init__.py
> 1.0.2 release

- docs/source/user/enforcing_limits.rst
- openwisp_radius/api/freeradius_views.py
- openwisp_radius/counters/base.py
- openwisp_radius/counters/mysql/__init__.py
- openwisp_radius/counters/mysql/daily_traffic_counter.py
- openwisp_radius/counters/mysql/monthly_traffic_counter.py
- openwisp_radius/counters/postgresql/__init__.py
- openwisp_radius/counters/postgresql/daily_traffic_counter.py
- openwisp_radius/counters/postgresql/monthly_traffic_counter.py
- openwisp_radius/counters/resets.py
- openwisp_radius/counters/sqlite/__init__.py
- openwisp_radius/counters/sqlite/daily_traffic_counter.py
- openwisp_radius/counters/sqlite/monthly_traffic_counter.py
- openwisp_radius/settings.py
- openwisp_radius/tests/test_api/test_freeradius_api.py
- openwisp_radius/tests/test_counters/test_base_counter.py
- openwisp_radius/tests/test_counters/test_mysql_counters.py
- openwisp_radius/tests/test_counters/test_postgresql_counters.py
- openwisp_radius/tests/test_counters/test_sqlite_counters.py
- Added a simple monthly traffic counter
- Added another optional alternative counter which starts counting the month from the date in which the user subscribed
Closes #449
> [feature] Added monthly counters #449

- openwisp_radius/admin.py
- openwisp_radius/tests/test_admin.py
- setup.py
- tests/openwisp2/settings.py
> [feature] Switched to autocomplete filters #462

- openwisp_radius/admin.py
- openwisp_radius/base/fields.py
- openwisp_radius/base/models.py
- openwisp_radius/migrations/0007_sms_verification.py
- openwisp_radius/migrations/0031_added_fallback_model_fields.py
- openwisp_radius/static/openwisp-radius/js/organization-setting-inline.js
- tests/openwisp2/sample_radius/migrations/0002_initial_openwisp_app.py
- tests/openwisp2/sample_radius/migrations/0028_alter_organizationradiussettings_allowed_mobile_prefixes_and_more.py
> [change] Grouped SMS features in organization admin #469

- docs/source/user/api.rst
- docs/source/user/settings.rst
- openwisp_radius/api/freeradius_views.py
- openwisp_radius/api/serializers.py
- openwisp_radius/api/urls.py
- openwisp_radius/api/views.py
- openwisp_radius/counters/base.py
- openwisp_radius/settings.py
- openwisp_radius/tests/test_api/test_api.py
- openwisp_radius/tests/test_counters/test_base_counter.py
- openwisp_radius/utils.py
- tests/openwisp2/sample_radius/api/views.py
> [feature] Added API endpoint to return user's RADIUS usage #499

- openwisp_radius/tasks.py
- openwisp_radius/tests/test_models.py
- Added error handling for NAS name not containing NAS subsnet
> [fix] Use counter's reply name for CoA

- openwisp_radius/management/commands/base/convert_called_station_id.py
- openwisp_radius/tests/test_commands.py
- openwisp_radius/tests/test_models.py
Fixed convert_called_station_id by org ID.
> [fix] Fixed convert_called_station_id by org ID

- docs/source/user/settings.rst
- openwisp_radius/api/freeradius_views.py
- openwisp_radius/api/serializers.py
- openwisp_radius/counters/base.py
- openwisp_radius/radclient/dictionary
- openwisp_radius/settings.py
- openwisp_radius/tasks.py
- openwisp_radius/tests/test_api/test_freeradius_api.py
- openwisp_radius/tests/test_batch_add_users.py
- openwisp_radius/tests/test_counters/test_sqlite_counters.py
- openwisp_radius/tests/test_models.py
This merely adds the possibility of creating custom counter classes that support gigawords.
Full support for gigawords will come in a future release.
> [change] Add rough support for gigawords

- openwisp_radius/api/serializers.py
- openwisp_radius/tests/test_api/test_freeradius_api.py
Certain NAS devices, such as hostapd, may omit input/output octets in accounting-stop requests. Consequently, FreeRADIUS represents these fields as empty strings in API requests to this API. Django REST Framework's validation rejects these requests as the fields are defined as Integer fields and do not accept empty strings.
This patch addresses this issue by gracefully handling empty strings, making the API more tolerant of varying system behaviors and enhancing compatibility across heterogeneous systems.
> [fix] Fix accounting stop handling for empty octets

- .github/workflows/ci.yml
- openwisp_radius/admin.py
- openwisp_radius/tests/test_admin.py
> [fix] Admin actions require model permissions

- .github/workflows/ci.yml
- setup.py
Run tests also if QA checks fail, pinned pydyf~=0.10.0.
> [ci] Run tests also if QA checks fail, pinned pydyf~=0.10.0

- docs/user/enforcing_limits.rst
Correct the module name spelling information
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/openwisp-radius/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
> Spelling correction

- .github/workflows/pypi.yml
Added workflow for publishing to PyPI
> [ci] Added workflow for publishing to PyPI

- docs/user/radius_monitoring.rst
- N/A I have manually tested the changes proposed in this pull request.
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
> [docs] Updated radius monitoring docs to include celerybeat schedule

- .github/workflows/version-branch.yml
- CHANGES.rst
- openwisp_radius/__init__.py
- requirements-test.txt
- setup.py
> [ci] Added GitHub workflow to replicate commits to version branch

- openwisp_radius/integrations/monitoring/apps.py
- openwisp_radius/integrations/monitoring/tests/test_admin.py
- openwisp_radius/integrations/monitoring/utils.py
> [fix] Improve query for RADIUS monitoring dashboard charts

- .github/workflows/ci.yml
- pyproject.toml
- setup.py
Related to https://github.com/IdentityPython/djangosaml2/issues/414.
> [deps] Bind djangosaml2 to 1.9.3 until Python 3.8 is dropped

- openwisp_radius/counters/resets.py
Small improvement for readability.
> [refactor] Improved readability of _monthly_subscription

- docs/developer/installation.rst
- openwisp_radius/base/models.py
- openwisp_radius/tests/test_commands.py
- run-qa-checks
- runtests
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
Let's make sure the instructions for running tests are up to date and easy to use.
> [tests] Added runtests script, updated docs

- openwisp_radius/settings.py
Removed old backward compatibility with django-freeradius.
> [chores] Removed old backward compatibility with django-freeradius
